### ISSUE TITLE
[tcp @ 0x2c608c10] Port missing in uri

### ISSUE THREAD

**Issue by yilawu** [gaodechen/webcam_yolov3_jetson_tx_hikvision#4]
I have run the detect.py successfully at ayooshkathuria/pytorch-yolo-v3 project.
Aftert changing cam_addrs at settings.py, I run the run.py then it went wrong.

**Comment by gaodechen** [comment]
As "port missing" suggests, maybe sth went wrong with the uri you use?
Have you run successfully with the same webcam uri at ayooshkathuria's repo? If so, please try "0" as uri which represents your local camera first to exclude bugs with stream pulling.

**Comment by yilawu** [comment]
> As "port missing" suggests, maybe sth went wrong with the uri you use?
> Have you run successfully with the same webcam uri at ayooshkathuria's repo? If so, please try "0" as uri which represents your local camera first to exclude bugs with stream pulling.

yeah, my settings config wrong.
